# Generated by Django 4.0.5 on 2022-07-04 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_newapp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Newapp',
        ),
    ]
