# Generated by Django 4.0.5 on 2022-07-04 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_newapp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newapp',
            name='newappdate',
        ),
    ]
