# Generated by Django 4.0.5 on 2022-07-19 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_newapp_newappdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
            ],
        ),
        migrations.AddField(
            model_name='newapp',
            name='newappdepart',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newapp',
            name='newappposition',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Addroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomname', models.CharField(max_length=122)),
                ('invigilatorsinroom', models.ManyToManyField(blank=True, to='home.newapp')),
            ],
        ),
        migrations.CreateModel(
            name='Addexam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examname', models.CharField(max_length=122)),
                ('examtype', models.CharField(max_length=122)),
                ('examsemtype', models.CharField(blank=True, max_length=122, null=True)),
                ('regularback', models.CharField(blank=True, max_length=122, null=True)),
                ('examcentre', models.CharField(max_length=122)),
                ('examdate', models.CharField(max_length=122)),
                ('newexamdate', models.DateField(blank=True, max_length=122, null=True)),
                ('examtime', models.CharField(max_length=122)),
                ('newexamtime', models.TimeField(blank=True, max_length=122, null=True)),
                ('examdesc', models.TextField()),
                ('examnewapp', models.ManyToManyField(blank=True, to='home.newapp')),
            ],
        ),
        migrations.CreateModel(
            name='Addbuilding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buildingname', models.CharField(max_length=122)),
                ('rooms', models.ManyToManyField(blank=True, to='home.addroom')),
            ],
        ),
    ]
