# Generated by Django 4.0.5 on 2022-07-04 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_newapp_newappdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='newapp',
            name='newappdepart',
            field=models.CharField(default='Department of Computer and Electronics Engineering', max_length=122),
        ),
    ]
