# Generated by Django 4.0.5 on 2022-07-05 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_newapp_newappdepart'),
    ]

    operations = [
        migrations.AddField(
            model_name='newapp',
            name='newappimage',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
