# Generated by Django 4.0.5 on 2022-07-05 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_newapp_newappimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newapp',
            name='newappimage',
            field=models.ImageField(upload_to='newimages/'),
        ),
    ]
