# Generated by Django 4.0.5 on 2022-07-07 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_remove_newapp_newappimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addexam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examname', models.CharField(max_length=122)),
                ('examtype', models.CharField(max_length=122)),
                ('examsemtype', models.CharField(max_length=122)),
                ('regularback', models.CharField(max_length=122)),
                ('examcentre', models.CharField(max_length=122)),
                ('examdate', models.CharField(max_length=122)),
                ('examtime', models.CharField(max_length=122)),
                ('examdesc', models.TextField(max_length=255)),
            ],
        ),
    ]
