# Generated by Django 4.0.5 on 2022-07-07 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_addexam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addexam',
            name='examdesc',
            field=models.TextField(),
        ),
    ]
