# Generated by Django 4.0.5 on 2022-07-07 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_addexam_examsemtype_alter_addexam_regularback'),
    ]

    operations = [
        migrations.AddField(
            model_name='addexam',
            name='examnewapp',
            field=models.ManyToManyField(blank=True, to='home.newapp'),
        ),
    ]
