# Generated by Django 4.0.5 on 2022-07-07 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_addexam_examnewapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addexam',
            name='examnewapp',
            field=models.ManyToManyField(blank=True, null=True, to='home.newapp'),
        ),
    ]
