# Generated by Django 4.0.5 on 2022-07-08 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_addexam_examnewapp_alter_addexam_examsemtype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addexam',
            name='examsemtype',
            field=models.CharField(blank=True, default='', max_length=122),
        ),
        migrations.AlterField(
            model_name='addexam',
            name='regularback',
            field=models.CharField(blank=True, default='', max_length=122),
        ),
    ]
