# Generated by Django 4.0.5 on 2022-07-08 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_alter_addexam_examsemtype_alter_addexam_regularback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addexam',
            name='regularback',
            field=models.CharField(blank=True, default='', max_length=122, null=True),
        ),
    ]
