# Generated by Django 4.0.5 on 2022-07-09 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_alter_addexam_examsemtype_alter_addexam_regularback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addexam',
            name='examsemtype',
            field=models.CharField(blank=True, max_length=122, null=True),
        ),
        migrations.AlterField(
            model_name='addexam',
            name='regularback',
            field=models.CharField(blank=True, max_length=122, null=True),
        ),
    ]
