# Generated by Django 4.0.5 on 2022-07-09 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_alter_addexam_examsemtype_alter_addexam_regularback'),
    ]

    operations = [
        migrations.AddField(
            model_name='addexam',
            name='newexamdate',
            field=models.DateField(blank=True, max_length=122, null=True),
        ),
    ]
