# Generated by Django 4.0.5 on 2022-07-09 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_addexam_newexamdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='addexam',
            name='newexamtime',
            field=models.TimeField(blank=True, max_length=122, null=True),
        ),
    ]
