# Generated by Django 4.0.5 on 2022-07-12 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_remove_addexam_examnewapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='addexam',
            name='examnewapp',
            field=models.ManyToManyField(blank=True, to='home.newapp'),
        ),
    ]
